/*
 * cytek_fmb_board.h
 *
 * Created: 2015/11/11/周三 13:37:43
 *  Author: ZRW cytek fmb board pin define here
 */ 


#ifndef CYTEK_FMB_BOARD_H_
#define CYTEK_FMB_BOARD_H_


#include "compiler.h"
#include "system_sams70.h"
#include "cytek_config.h"

/*----------------------------------------------------------------------------*/
/**
 *  \page CYTEK_FMB_BOARD - Operating frequencies"
 *  This page lists several definition related to the board operating frequency
 *
 *  \section Definitions
 *  - \ref BOARD_FREQ_*
 *  - \ref BOARD_MCK
 */

/** Board oscillator settings */
#define BOARD_FREQ_SLCK_XTAL            (32768U)
#define BOARD_FREQ_SLCK_BYPASS          (32768U)
#define BOARD_FREQ_MAINCK_XTAL          (12000000U)
#define BOARD_FREQ_MAINCK_BYPASS        (12000000U)

/** Master clock frequency */
#define BOARD_MCK                       CHIP_FREQ_CPU_MAX

/** board main clock xtal statup time */
#define BOARD_OSC_STARTUP_US            15625



/** Name of the board */
#define BOARD_NAME "CYTEK_FMB_BOARD"
/** Family definition (already defined) */
#define sams70
/** Core definition */
#define cortexm7


/*------------------------cytek fmb board pin define START---------------------------*/
//define debug port interface
#define CONSOLE_UART               USART1
#define CONSOLE_UART_ID            ID_USART1 


#ifdef  CYTEK_FMB_CONSOLE_USART1
/** USART1 pins definitions, PA21,PB4. */
#define UART_RXD_GPIO   PIO_PA21_IDX
#define UART_RXD_FLAGS  IOPORT_MODE_MUX_A
#define UART_TXD_GPIO   PIO_PB4_IDX
#define UART_TXD_FLAGS  IOPORT_MODE_MUX_D
#endif

#ifdef  CYTEK_FMB_CONSOLE_UART0
/** UART0 pins definitions, PA9,PA10. */
#define UART_RXD_GPIO   PIO_PA9_IDX
#define UART_RXD_FLAGS  IOPORT_MODE_MUX_A
#define UART_TXD_GPIO   PIO_PA10_IDX
#define UART_TXD_FLAGS  IOPORT_MODE_MUX_A
#endif

/** USART0 pins definitions, PB0,PB1. */
//#define USART0_RXD_GPIO   PIO_PB0_IDX
//#define USART0_RXD_FLAGS  IOPORT_MODE_MUX_C
//#define USART0_TXD_GPIO   PIO_PB1_IDX
//#define USART0_TXD_FLAGS  IOPORT_MODE_MUX_C


/*! \name GPIO PE3 Connections of VBUS monitoring
 */
//! @{
#define USB_VBUS_FLAGS         (PIO_INPUT | PIO_PULLUP)
#define USB_VBUS_PIN             PIO_PE3_IDX  /* As IO pin input */
#define USB_DETECT_PIN  		PIO_PE3_IDX
#define USB_VBUS_PIN_IRQn ( PIOE_IRQn)
#define USB_VBUS_PIO_ID       ID_PIOE
#define USB_VBUS_PIO_MASK  PIO_PE3
//! @}


#ifdef CYTEK_FMB_SPI0
/** SPI0 pins definition */
#define SPI0_MISO_GPIO    PIO_PD20_IDX
#define SPI0_MISO_FLAGS  (IOPORT_MODE_MUX_B)
#define SPI0_MOSI_GPIO    PIO_PD21_IDX
#define SPI0_MOSI_FLAGS  (IOPORT_MODE_MUX_B)
#define SPI0_NPCS0_GPIO   PIO_PB2_IDX
#define SPI0_NPCS0_FLAGS  (IOPORT_MODE_MUX_D)
#define SPI0_NPCS1_GPIO   PIO_PA31_IDX
#define SPI0_NPCS1_FLAGS  (IOPORT_MODE_MUX_A)
#define SPI0_SPCK_GPIO    PIO_PD22_IDX
#define SPI0_SPCK_FLAGS  (IOPORT_MODE_MUX_B)

#define SPI0_DEV_RESET            (PIO_PD17_IDX)
#define SPI0_DEV_RESET_ACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SPI0_DEV_RESET_INACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define SPI0_DEV_LADC        (PIO_PD18_IDX)
#define SPI0_DEV_LADC_ACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SPI0_DEV_LADC_INACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
#endif


#ifdef CYTEK_FMB_SPI1
/** SPI1 pins definition */
#define SPI1_SPCK_GPIO    PIO_PC24_IDX
#define SPI1_SPCK_FLAGS  (IOPORT_MODE_MUX_C)
#define SPI1_NPCS0_GPIO    PIO_PC25_IDX
#define SPI1_NPCS0_FLAGS  (IOPORT_MODE_MUX_C)
#define SPI1_MISO_GPIO    PIO_PC26_IDX
#define SPI1_MISO_FLAGS  (IOPORT_MODE_MUX_C)
#define SPI1_NPCS1_GPIO   PIO_PC28_IDX
#define SPI1_NPCS1_FLAGS  (IOPORT_MODE_MUX_C)
#define SPI1_NPCS2_GPIO   PIO_PC29_IDX
#define SPI1_NPCS2_FLAGS  (IOPORT_MODE_MUX_C)
#endif


#ifdef CYTEK_FMB_QSPI
/** QSPI pins definition */
#define QSPI_QCS_GPIO     PIO_PA11_IDX
#define QSPI_QCS_FLAGS    (IOPORT_MODE_MUX_A)
#define QSPI_QIO1_GPIO    PIO_PA12_IDX
#define QSPI_QIO1_FLAGS   (IOPORT_MODE_MUX_A)
#define QSPI_QIO0_GPIO    PIO_PA13_IDX
#define QSPI_QIO0_FLAGS   (IOPORT_MODE_MUX_A)
#define QSPI_QSCK_GPIO    PIO_PA14_IDX
#define QSPI_QSCK_FLAGS   (IOPORT_MODE_MUX_A)
#define QSPI_QIO2_GPIO    PIO_PA17_IDX
#define QSPI_QIO2_FLAGS   (IOPORT_MODE_MUX_A)
#define QSPI_QIO3_GPIO    PIO_PD31_IDX
#define QSPI_QIO3_FLAGS   (IOPORT_MODE_MUX_A)
#endif


#ifdef CYTEK_FMB_TWIHS1
/** TWI1 pins definition */
#define TWIHS1_DATA_GPIO   PIO_PA3_IDX
#define TWIHS1_DATA_FLAGS  (IOPORT_MODE_MUX_A)
#define TWIHS1_CLK_GPIO    PIO_PA4_IDX
#define TWIHS1_CLK_FLAGS   (IOPORT_MODE_MUX_A)
#endif  //CYTEK_FMB_TWIHS1



#ifdef CYTEK_FMB_TWIHS2
/** TWI2 pins definition */
#define TWIHS2_DATA_GPIO   PIO_PD27_IDX
#define TWIHS2_DATA_FLAGS  (IOPORT_MODE_MUX_C)
#define TWIHS2_CLK_GPIO    PIO_PD28_IDX
#define TWIHS2_CLK_FLAGS   (IOPORT_MODE_MUX_C)
#endif

/** GPIO functions pin define*/

#ifdef CYTEK_FMB_IO_LED
//! \name LED definitions
//@{
#define LED1_GPIO            (PIO_PD5_IDX)
#define LED1_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED1_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED2_GPIO            (PIO_PD4_IDX)
#define LED2_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED2_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED3_GPIO            (PIO_PD3_IDX)
#define LED3_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED3_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED4_GPIO            (PIO_PA29_IDX)
#define LED4_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED4_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED5_GPIO            (PIO_PD2_IDX)
#define LED5_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED5_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED6_GPIO            (PIO_PD1_IDX)
#define LED6_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED6_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED7_GPIO            (PIO_PD0_IDX)
#define LED7_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED7_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED8_GPIO            (PIO_PE0_IDX)
#define LED8_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED8_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED9_GPIO            (PIO_PE1_IDX)
#define LED9_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED9_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define LED10_GPIO            (PIO_PE2_IDX)
#define LED10_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define LED10_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
//@}
#endif

#ifdef CYTEK_FMB_PUMP
//GPIO: pump enable
//@{
#define PUMP1_GPIO            (PIO_PD6_IDX)
#define PUMP1_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define PUMP1_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define PUMP2_GPIO            (PIO_PD7_IDX)
#define PUMP2_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define PUMP2_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define PUMP3_GPIO            (PIO_PA30_IDX)
#define PUMP3_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define PUMP3_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
//}@
#endif

#ifdef CYTEK_FMB_LASER
//GPIO: laser enable@{
#define LASER1_GPIO            (PIO_PE5_IDX)
#define LASER1_ACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)   ///??
#define LASER1_INACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)   //??

#define LASER2_GPIO            (PIO_PA22_IDX)
#define LASER2_ACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)  //??
#define LASER2_INACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)  //??

#define LASER3_GPIO            (PIO_PD30_IDX)
#define LASER3_ACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)  //??
#define LASER3_INACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH) //??
//}@
#endif

#ifdef CYTEK_FMB_POWER_STATE
#define POWERGOOD_GPIO            (PIO_PA23_IDX)
#define POWERGOOD_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define POWERGOOD_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define STATEGOOD_GPIO            (PIO_PA16_IDX)
#define STATEGOOD_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define STATEGOOD_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
#endif


#ifdef  CYTEK_FMB_SOLENOID
//**solenoid
//@{
#define SOLENOID1_GPIO            (PIO_PE4_IDX)
#define SOLENOID1_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SOLENOID1_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define SOLENOID2_GPIO            (PIO_PA18_IDX)
#define SOLENOID2_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SOLENOID2_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define SOLENOID3_GPIO            (PIO_PA19_IDX)
#define SOLENOID3_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SOLENOID3_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define SOLENOID4_GPIO            (PIO_PA20_IDX)
#define SOLENOID4_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SOLENOID4_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define SOLENOID5_GPIO            (PIO_PB0_IDX)
#define SOLENOID5_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SOLENOID5_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)

#define SOLENOID6_GPIO            (PIO_PB1_IDX)
#define SOLENOID6_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define SOLENOID6_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
//solenoid}@
#endif


#ifdef CYTEK_FMB_MOTOR
//motor en{
#define MOTOR_DIR_UP    (IOPORT_PIN_LEVEL_LOW)
#define MOTOR_DIR_DOWN		(IOPORT_PIN_LEVEL_HIGH)

#define MOTOR1  (1)
#define MOTOR1_GPIO            (PIO_PC12_IDX)
#define MOTOR1_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define MOTOR1_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
#define MOTOR1_DIR  (PIO_PC13_IDX)
#define MOTOR1_PULL (PIO_PC15_IDX)
#define MOTOR1_PULL_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_HIGH)
#define MOTOR1_PULL_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_LOW)

#define MOTOR2  (2)
#define MOTOR2_GPIO            (PIO_PC0_IDX)
#define MOTOR2_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_LOW)
#define MOTOR2_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_HIGH)
#define MOTOR2_DIR  (PIO_PC30_IDX)
#define MOTOR2_PULL (PIO_PC31_IDX)
#define MOTOR2_PULL_INACTIVE_LEVEL    (IOPORT_PIN_LEVEL_HIGH)
#define MOTOR2_PULL_ACTIVE_LEVEL  (IOPORT_PIN_LEVEL_LOW)

//motor}@
#endif


#ifdef  CYTEK_FMB_SENSOR_INPUT
#define SENSOR1_GPIO       (PIO_PC20_IDX)
#define SENSOR1_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR1_SENSE (IOPORT_SENSE_RISING)

#define SENSOR2_GPIO       (PIO_PC18_IDX)
#define SENSOR2_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR2_SENSE (IOPORT_SENSE_RISING)

#define SENSOR3_GPIO       (PIO_PC22_IDX)
#define SENSOR3_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR3_SENSE (IOPORT_SENSE_RISING)

#define SENSOR4_GPIO       (PIO_PC17_IDX)
#define SENSOR4_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR4_SENSE (IOPORT_SENSE_RISING)

#define SENSOR5_GPIO       (PIO_PC14_IDX)
#define SENSOR5_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR5_SENSE (IOPORT_SENSE_RISING)

#define SENSOR6_GPIO       (PIO_PC10_IDX)
#define SENSOR6_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR6_SENSE (IOPORT_SENSE_RISING)

#define SENSOR7_GPIO       (PIO_PC8_IDX)
#define SENSOR7_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR7_SENSE (IOPORT_SENSE_RISING)

#define SENSOR8_GPIO       (PIO_PC5_IDX)
#define SENSOR8_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR8_SENSE (IOPORT_SENSE_RISING)

#define SENSOR9_GPIO       (PIO_PC4_IDX)
#define SENSOR9_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR9_SENSE (IOPORT_SENSE_RISING)

#define SENSOR10_GPIO       (PIO_PC2_IDX)
#define SENSOR10_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR10_SENSE (IOPORT_SENSE_RISING)

#define SENSOR11_GPIO       (PIO_PC19_IDX)
#define SENSOR11_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR11_SENSE (IOPORT_SENSE_RISING)

#define SENSOR12_GPIO       (PIO_PC21_IDX)
#define SENSOR12_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR12_SENSE (IOPORT_SENSE_RISING)

#define SENSOR13_GPIO       (PIO_PC23_IDX)
#define SENSOR13_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR13_SENSE (IOPORT_SENSE_RISING)

#define SENSOR14_GPIO       (PIO_PC16_IDX)
#define SENSOR14_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR14_SENSE (IOPORT_SENSE_RISING)

#define SENSOR15_GPIO       (PIO_PC11_IDX)
#define SENSOR15_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR15_SENSE (IOPORT_SENSE_RISING)

#define SENSOR16_GPIO       (PIO_PC9_IDX)
#define SENSOR16_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR16_SENSE (IOPORT_SENSE_RISING)

#define SENSOR17_GPIO       (PIO_PC6_IDX)
#define SENSOR17_FLAGS (IOPORT_MODE_PULLDOWN)
#define SENSOR17_SENSE (IOPORT_SENSE_FALLING)

#define SENSOR18_GPIO       (PIO_PC7_IDX)
#define SENSOR18_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR18_SENSE (IOPORT_SENSE_RISING)

#define SENSOR19_GPIO       (PIO_PC3_IDX)
#define SENSOR19_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR19_SENSE (IOPORT_SENSE_RISING)

#define SENSOR20_GPIO       (PIO_PC1_IDX)
#define SENSOR20_FLAGS (IOPORT_MODE_PULLUP | IOPORT_MODE_DEBOUNCE)
#define SENSOR20_SENSE (IOPORT_SENSE_RISING)
#endif //define CYTEK_SENSOR_INPUT

//#ifdef CYTEK_FMB_FLOW_METER
/** TWI0 pins definition */
#define TWIHS0_DATA_GPIO   PIO_PA3_IDX
#define TWIHS0_DATA_FLAGS  (IOPORT_MODE_MUX_A)
#define TWIHS0_CLK_GPIO    PIO_PA4_IDX
#define TWIHS0_CLK_FLAGS   (IOPORT_MODE_MUX_A)



/*------------------------cytek fmb board pin define END------------------------------*/


#endif /* CYTEK_FMB_BOARD_H_ */

