/*
 * cytek_fmb_global_err_table.h
 *
 * Created: 2015/11/30/周一 14:09:23
 *  Author: lenovo
 */ 


#ifndef CYTEK_FMB_GLOBAL_ERR_TABLE_H_
#define CYTEK_FMB_GLOBAL_ERR_TABLE_H_

enum cytek_fmb_state {
	STATE_OK,
	MALLOC_NO_MEM,
/***************flash code is ok******************/
	FLASH_OK ,
	FLASH_ERROR_INIT,
	FLASH_ERROR_ID,	
	FLASH_ERROR_INVALID_ADDR,
	FLASH_ERROR_MEM_OVERFLOW,
	FLASH_ERROR_PAGE_ERASE_FAILED,
	FLASH_ERROR_INVALID_PAGENR,
	FLASH_ERROR_INVALID_SUBSECTORNR,
	FLASH_ERROR_INVALID_SECTORNR,
	FLASH_ERROR_PROGRAM_FAILED,
	FLASH_SECTOR_PROTECTED,
	FLASH_SECTOR_UNPROTECTED,
	FLASH_ERROR_SECTORPROTECTED_FAILED,
	FLASH_ERROR_SECTORUNPROTECTED_FAILED,
	FLASH_SECTOR_LOCKED,
	FLASH_SECTOR_UNLOCKED,
	FLASH_ERROR_SECTOR_LOCKDOWN_FAILED,
	FLASH_TIMEOUT,
	FLASH_OPERATION_ONGONING,
	FLASH_SECTOR_PROTECT,
/***************end of flash code******************/
};

#endif /* CYTEK_FMB_GLOBAL_ERR_TABLE_H_ */